name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    compiler: gcc
    gcc: 13

    steps:
    - uses: actions/checkout@v3

    - name: Update apt-get
      run: sudo apt-get update

    - name: Update gnu compiler
      run: 

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Install lcov
      run: sudo apt-get install lcov

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_COVERAGE:BOOL=TRUE -DBUILD_TESTS:BOOL=TRUE -DBUILD_DEMOS:BOOL=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

    # Code coverage
    - name: Capture coverage info
      run: lcov --directory . --capture --output-file coverage.info
     
    - name: Output coverage data for debugging
      run: lcov --list coverage.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.info

