name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # ==================
    # Install and update
    # ==================

    - name: Update apt-get
      run: sudo apt-get update

    - name: Update and install
      run: sudo apt-get install -y g++-13 llvm clang-16 cmake lcov doxygen

    - name: Make sure clang++ is set properly
      run: sudo ln -s /usr/bin/clang-16 /usr/bin/clang && sudo ln -s /usr/bin/clang++-16 /usr/bin/clang++
      

      
    # ================================
    # Build/run/test/coverage
    # ================================

    # Ensure script is executable
    - name: Make build script executable
      run: chmod +x build-run-cov.sh


    # gcc
    - name: Run build/run/test/coverage script
      run: TC=gcc ${{github.workspace}}/./build-run-cov.sh

    # clang
    - name: Run build/run/test/coverage script
      run: TC=clang ${{github.workspace}}/./build-run-cov.sh


    # ====================
    # Upload code coverage
    # ====================

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{github.workspace}}/gcc-build/gcc-coverage.info ${{github.workspace}}/build/clang-coverage.info

