name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # ==================
    # Install and update
    # ==================

    - name: Update apt-get
      run: sudo apt-get update

    - name: Update and install      
      run: sudo apt-get install -y g++-13 cmake lcov doxygen

    # https://github.com/llvm/llvm-project/issues/64182#issuecomment-1658085767
    - name: Apply workaround for llvm bug
      run: sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14
      
    - name: Install latest llvm
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16

    # ================================
    # Build/run/test/coverage
    # ================================

    # Ensure script is executable
    - name: Make build script executable
      run: chmod +x build-run-cov.sh


    # gcc
    # - name: Run build/run/test/coverage script
    #   run: TC=gcc ${{github.workspace}}/./build-run-cov.sh

    # clang
    - name: Run build/run/test/coverage script
      run: TC=clang ${{github.workspace}}/./build-run-cov.sh


    # ====================
    # Upload code coverage
    # ====================

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{github.workspace}}/build/clang-coverage.info

